/* Embedded rootCA.crt (auto-generated by scripts/build.ps1 from the active root cert).
   中心端重签根证书后, 下次构建自动同步本文件; 请勿手工编辑。 */
static const char *EMBEDDED_PEM =
    "-----BEGIN CERTIFICATE-----\n"
    "MIIBjTCCATOgAwIBAgIBATAKBggqhkjOPQQDAjAuMREwDwYDVQQKEwhZdWdzaWdo\n"
    "dDEZMBcGA1UEAxMQWXVnc2lnaHQgUm9vdCBDQTAeFw0yNjA5MjkxNDU5MDJaFw0z\n"
    "NjA5MjkxNTU5MDJaMC4xETAPBgNVBAoTCFl1Z3NpZ2h0MRkwFwYDVQQDExBZdWdz\n"
    "aWdodCBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEoSbvDFWX+kTs\n"
    "vdWrXPEwwnd0x5cz+h456VU5awAaYygXrr6xVuWYKX9BLeY3pFeHu591DRSaNeeW\n"
    "q0F/q03f16NCMEAwDgYDVR0PAQH/BAQDAgKEMA8GA1UdEwEB/wQFMAMBAf8wHQYD\n"
    "VR0OBBYEFLtU1uAYJ2AO93RFFyOtQv6jIG+4MAoGCCqGSM49BAMCA0gAMEUCIQDS\n"
    "Kmgq83yZK2ALOXMWirtL3nkGP9K50zsehSNefqpoxAIgEI4tbaF6667Xf/TS4CB1\n"
    "kTrrHnRbjyxwQOmGD9q2CVE=\n"
    "-----END CERTIFICATE-----\n"
    "";
